alias home="cd ~"
alias dotfiles="cd $HOME/.config"
alias zshconfig="nvim ~/.zshrc"
alias nvimconfig="nvim ~/.config/nvim/ . "
alias zshsource="source ~/.zshrc"
alias mypod="ssh $POD_NAME"
alias fzfp="fzf --preview 'bat  --color=always {}'"
alias docs="cd ~/Documents"
alias downloads="cd ~/Downloads"
alias python="python3"
alias cat="bat"
alias nv="nvim ."
